### ISSUE TITLE
Convert ERB templates into HAML

### ISSUE THREAD

**Issue by DeadSuperHero** [DeadSuperHero/askwise#18]
The templates are starting to look pretty ugly. Let's increase code readability!

**Comment by DeadSuperHero** [comment]
Prioritizing this.

**Comment by maxwell** [comment]
If you want your app to be open source, I'd recommend against this!  Only ruby people know HAML, and everyone knows HTML!

**Comment by DeadSuperHero** [comment]
That's interesting! I mainly just wanted to practice cleaning up view
templates for readability and formal organization. If HTML is preferable,
I'll stick with it.

**Comment by maxwell** [comment]
many editors have erb code cleanup, on rubymine, it is cntl option + L on mac
